name: Deploy Components to Mainnet
on:
  push:
    branches: [main]
jobs:
  deploy-mainnet:
    uses: NEARBuilders/bos-workspace/.github/workflows/deploy.yml@feat/git-workflows
    with:
      deploy-env: "mainnet"
      app-name: "discoverbos"
      deploy-account-address:  ${{ vars.DEPLOY_ACCOUNT_ID }}
      signer-account-address: ${{ vars.SIGNER_ACCOUNT_ID }}
      signer-public-key: ${{ vars.SIGNER_PUBLIC_KEY }}
    secrets:
      SIGNER_PRIVATE_KEY:  ${{ secrets.SIGNER_PRIVATE_KEY }}